### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by arjunadotfusion** [agility/Agility-AspNetCore-ReactSampleSite#1]
I followed the instructions in the readme to a T, however I do get the following error that seems to originate in Agility.Web.

I am running `dotnet` version `3.0.100`.

Webpack seems to run fine.

```
 Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.AggregateException: One or more errors occurred. (Check your settings in the or the Website name and Security key in the web.config.  The provided security key is not valid.) ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Check your settings in the or the Website name and Security key in the web.config.  The provided security key is not valid.
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Agility.Web.BaseCache.GetItem[TAgilityItem](AgilityItemKey itemKey, String websiteName, Boolean forceGetFromServer)
   at Agility.Web.BaseCache.GetItem[TAgilityItem](AgilityItemKey itemKey, String websiteName)
   at Agility.Web.BaseCache.GetDomainConfiguration(String websiteName)
   at Agility.Web.Data.GetConfig()
   at Agility.Web.AgilityContext.get_Domain()
   at Agility.Web.AgilityContext.get_LanguageCode()
   at Agility.Web.Data.GetAgilityVaryByCustomString(HttpContext context)
   at Agility.Web.Caching.AgilityResponseCacheMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
---> (Inner Exception #0) System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Check your settings in the or the Website name and Security key in the web.config.  The provided security key is not valid. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.Exception: Check your settings in the or the Website name and Security key in the web.config.  The provided security key is not valid.
   at Agility.ContentServer.AgilityContentServer.GetAgilityItemsForStaging(AgilityWebsiteAuthorization auth, AgilityItemKey[] itemKeys) in d:\a\9\s\Agility CMS 2014\ContentServer\AgilityContentServer.cs:line 711
   at SyncInvokeGetAgilityItemsForStaging(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)).<---
```

**Comment by joelvarty** [comment]
Sounds like your appsettings.json file isn't being loaded - this could be an issue with .Net core 3 - have you tried using 2.2?

**Comment by arjunadotfusion** [comment]
Thanks. That did it.
